name: Build Windows EXE

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest  # Windows OS required
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant gradlew permissions
        run: chmod +x gradlew  # Fixes permission issues on Windows

      - name: Build EXE
        run: ./gradlew :desktopApp:packageExe  # Or use `createExe`

      - name: Upload EXE
        uses: actions/upload-artifact@v3
        with:
          name: YourApp.exe
          path: desktopApp/build/compose/binaries/main/release/YourApp.exe
