name: Build Windows EXE

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest  # Windows runner required for EXE
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant gradlew permissions
        run: chmod +x gradlew

      - name: Build EXE
        run: ./gradlew :desktop:packageExe  # Note: Your module is named "desktop"

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: YourApp.exe
          path: desktop/build/compose/binaries/main/release/com.vanshika.multiplatformproject.exe
